from __future__ import annotations
import json
from datetime import datetime

from .models import ClaimNote
from .storage import KnowledgeStore


def export_claude_context(store: KnowledgeStore) -> str:
    """Export all wiki notes as a Markdown block for Claude project context."""
    lines = [
        "# LAB Knowledge OS — AI Context Export",
        f"_Generated: {datetime.utcnow().isoformat()}_",
        "",
    ]

    for note_type, heading in [("entity", "## Entities"), ("claim", "## Claims"), ("summary", "## Summaries")]:
        notes = store.list_notes(note_type)
        if not notes:
            continue
        lines.append(heading)
        for note in notes:
            confidence_pct = f"{int(note.confidence * 100)}%"
            reviewed = "human-reviewed" if note.human_reviewed else "pending review"
            lines.append(f"\n### {note.id} [{note.type}] confidence={confidence_pct} {reviewed}")
            lines.append(f"_Generated by {note.generated_by} at {note.generated_at.isoformat()}_")
            if note.source_ids:
                lines.append(f"_Sources: {', '.join(note.source_ids)}_")
            if note.tags:
                lines.append(f"_Tags: {', '.join(note.tags)}_")
            lines.append("")
            lines.append(note.content_markdown)
            if isinstance(note, ClaimNote):
                lines.append(f"\n**Claim:** {note.claim_text}")
                lines.append(f"**Status:** {note.status}")
                if note.evidence:
                    lines.append("**Evidence:**")
                    for ev in note.evidence:
                        ev_d = ev.to_dict() if hasattr(ev, "to_dict") else ev
                        lines.append(
                            f"  - source={ev_d['source_id']} "
                            f"quote=\"{ev_d['quote']}\" location={ev_d['location']}"
                        )
        lines.append("")

    return "\n".join(lines)


def export_chatgpt_context(store: KnowledgeStore) -> str:
    """Export all wiki notes as a JSON string for ChatGPT custom instructions."""
    payload: dict = {
        "generated_at": datetime.utcnow().isoformat(),
        "entities": [],
        "claims": [],
        "summaries": [],
    }
    for note_type in ("entity", "claim", "summary"):
        for note in store.list_notes(note_type):
            payload[f"{note_type}s"].append(note.to_dict())
    return json.dumps(payload, indent=2)


def export_source_index(store: KnowledgeStore) -> str:
    """Export a Markdown table of all ingested sources."""
    lines = [
        "# LAB Knowledge OS — Source Index",
        f"_Generated: {datetime.utcnow().isoformat()}_",
        "",
        "| Source ID | Original Path | MIME | Ingested At | Hash (prefix) |",
        "|-----------|---------------|------|-------------|---------------|",
    ]
    for src in store.list_sources():
        lines.append(
            f"| {src.source_id} | {src.original_path} | {src.mime_type} "
            f"| {src.ingested_at.isoformat()} | {src.hash[:12]}... |"
        )
    return "\n".join(lines)
